apiVersion: v1
kind: Namespace
metadata:
  name: c2c-guardant-yury-java-gradle-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-guardant-yury-java-gradle-deployment
  namespace: c2c-guardant-yury-java-gradle-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:266e2f3262a80f737211addabc7ab58de63640bc

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-guardant-yury-java-gradle-label
  name: c2c-guardant-yury-java-gradle-service
  namespace: c2c-guardant-yury-java-gradle-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---